//
//  Snippets.h
//  iSH-AOK
//
//  A library of saved command lines, opened as a sheet over the terminal (long
//  press the Paste key, or Cmd-J), so a command you run constantly is one tap
//  instead of a phone keyboard's worth of typing. It is the feature dedicated
//  SSH clients call "snippets", and it is the thing AOK was missing for anyone
//  using it as their terminal for OTHER machines: over ssh, the local shell's
//  aliases, functions and history are all on the wrong side of the connection.
//
//  Two decisions shape the whole thing.
//
//  A snippet is INSERTED, not run. Tapping one puts the text on the command
//  line and leaves the cursor sitting there; running it is a separate per
//  snippet opt-in (kISHSnippetRun). A library of saved commands that fire on a
//  mis-tap is a library of ways to destroy something, and the snippets worth
//  saving -- the long ones, with the flags nobody remembers -- are exactly the
//  ones worth reading once before they run.
//
//  The library lives in two places at once. NSUserDefaults is what the sheet
//  reads and writes, because the sheet has to work with the guest shut down. A
//  JSON mirror at /AOK/persist/snippets.json is what the GUEST sees, so
//  snippets can be edited in vi, kept in git, generated by a script, and shared
//  between roots -- /AOK/persist is realfs-backed and mounted shared, so one
//  library follows you from Alpine to Devuan. That mirror is the part no hosted
//  SSH client can offer, and +[ISHSnippetStore syncWithGuest:] documents which
//  side wins when both have changed.
//

#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

#pragma mark Model

// Keys in a snippet dictionary. `run` is an NSNumber-wrapped BOOL; the rest are
// strings. `id` is a UUID string that survives renames, so an edit updates the
// snippet the user opened rather than appending a near-duplicate.
extern NSString *const kISHSnippetID;
extern NSString *const kISHSnippetName;
extern NSString *const kISHSnippetText;
extern NSString *const kISHSnippetRun;

// Where the guest-visible mirror lives. /AOK/persist rather than a home
// directory: it is realfs-backed (so writing it does not need the guest VFS to
// walk a fakefs tree), it already exists whenever the app has mounted anything,
// and it is shared across roots, which is what makes the library follow the
// user rather than the rootfs.
extern NSString *const kISHSnippetsGuestPath;

@interface ISHSnippetStore : NSObject

// The library, newest edits last. Never nil.
+ (NSArray<NSDictionary<NSString *, id> *> *)snippets;
+ (void)setSnippets:(NSArray<NSDictionary<NSString *, id> *> *)snippets;

// A new snippet with a fresh id. Does not save it.
+ (NSDictionary<NSString *, id> *)snippetWithName:(NSString *)name
                                             text:(NSString *)text
                                              run:(BOOL)run;

// Upsert by id; a snippet whose id is not already in the library is appended.
// Exports to the guest mirror afterwards.
+ (void)saveSnippet:(NSDictionary<NSString *, id> *)snippet;
+ (void)deleteSnippetWithID:(NSString *)identifier;

// Reconcile with the guest mirror, then call back on the MAIN queue.
//
// The rule, in one line: the guest file wins when it has changed since we last
// wrote it, and otherwise we write it. That is decided by digest rather than by
// timestamp -- a modification date on a fakefs file that several roots can
// touch is not evidence of anything, while "these bytes are not the bytes we
// left there" is. A file we cannot parse is left strictly alone and nothing is
// exported over it, because a half-finished edit in vi is still the user's
// work; `libraryChanged` is NO in that case, the same as for any other no-op.
//
// Cheap and safe to call when the guest is down: it answers NO immediately.
+ (void)syncWithGuest:(nullable void (^)(BOOL libraryChanged))completion;

@end

// JSON encoding of the mirror. Pretty-printed with sorted keys so that a `git
// diff` of the file is readable and stable. Exposed for the unit test.
extern NSData *_Nullable ISHSnippetsEncodeJSON(NSArray<NSDictionary<NSString *, id> *> *snippets);
// Decodes, tolerating a hand-written file: a snippet may omit `id` (one is
// generated) and `run` (defaults to NO), entries that are not objects or have
// no text are dropped, and a document that is not an array of objects at all
// returns nil so the caller can leave the file alone.
extern NSArray<NSDictionary<NSString *, id> *> *_Nullable ISHSnippetsDecodeJSON(NSData *_Nullable data);

#pragma mark Sheet

@class ISHSnippetsViewController;

@protocol ISHSnippetsDelegate <NSObject>

// Put a snippet on the command line. `execute` asks for it to RUN.
//
// The sheet never builds the bytes itself -- it does not know whether the guest
// has bracketed paste mode on, and that decides both how the text is wrapped
// and where the newline that runs it has to go. Same dumb-pipe split the file
// browser uses, just with one more thing to say.
- (void)snippets:(ISHSnippetsViewController *)snippets
      insertText:(NSString *)text
         execute:(BOOL)execute;

@optional

// The sheet has gone away; the presenter uses this to take keyboard focus back.
- (void)snippetsDidDismiss:(ISHSnippetsViewController *)snippets;

@end

@interface ISHSnippetsViewController : UITableViewController

+ (void)presentFromViewController:(UIViewController *)presenter
                         delegate:(nullable id<ISHSnippetsDelegate>)delegate;

@property (nonatomic, weak) id<ISHSnippetsDelegate> delegate;

@end

NS_ASSUME_NONNULL_END
