#!/usr/bin/env python3
"""Make dash's globals thread-local, so two native dashes can be live at once.

WHY. A native program in iSH-AOK is a C function on a guest task's thread, not
a process (kernel/native.c). dash's fork-by-relaunch makes the child a second
guest task -- so a second dash, on a second thread, in the SAME address space
as its parent, which is still sitting in waitforjob(). With ordinary statics the
child's setvar() writes the parent's variable table and its popredir() unwinds
the parent's redirection list. bash and zsh crossed this bridge first
(tools/bash-tls-fix-statics.py, tools/bash-tls-fix-externs.py); this is dash's,
and it is one file rather than three because dash has 105 mutable globals where
bash had thousands.

HOW. The names come from the linker, not from parsing C: `nm -m` says which
section each symbol landed in, and a mutable symbol in __DATA,__data/__bss or
(common) is precisely a global that is still shared. No guessing about what is
a declaration and what is a use, and nothing to drift.

The insertion is a real declaration scan -- brace depth, comments and strings
tracked -- because dash declares things this cannot be regexed out of:

    struct var varinit[] = {          /* spans 20 lines */
    MKINIT char *trap[NSIG];          /* macro before the type */
    char linenovar[sizeof("LINENO=")+sizeof(int)*CHAR_BIT/3+1] = "LINENO=";

A declaration missed in a header is NOT a compile error when the definition is
in another translation unit -- it is a silent read of the wrong memory. That is
what tools/check-bash-tls.py exists to catch, and it covers build/libdash.a.
"""

import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENDOR = os.path.join(REPO, "deps", "dash", "src")
# src/bltin/ holds printf, test and times -- separate files with globals of
# their own (t_wp, gargv), so the walk covers both directories or misses them.
DIRS = (VENDOR, os.path.join(VENDOR, "bltin"))
OBJDIR = os.path.join(REPO, "build", "libdash.a.p")
# The names, checked in, so a re-run does not depend on the build being
# pristine. It cannot: once the conversion has been applied the symbols are in
# __DATA,__thread_vars and `nm` no longer reports them as shared, so a second
# run over a half-converted build sees a SHORTER list and leaves the rest
# behind -- which is how parsefile ended up shared while basepf was not.
#
# It is also what makes the tool re-runnable at all. dash generates init.c,
# nodes.c, builtins.c, signames.c and syntax.c from its own helper programs;
# re-running `make prep` in deps/dash overwrites them WITHOUT the conversion,
# and re-running this tool is the fix.
#
# Regenerate with --refresh, from a build of the UNCONVERTED tree only.
MANIFEST = os.path.join(REPO, "tools", "dash-tls-globals.txt")

# Deliberately shared. Each of these is read-only in practice, and every one of
# them is the ADDRESS half of a constant initializer somewhere -- the address of
# a thread-local is not a compile-time constant, so converting them would force
# a runtime fixup to isolate a value nothing ever writes.
ALLOW = {
    # mystring.c: `char nullstr[1]` -- the zero-length string. Its ADDRESS is
    # the value: jobs.c stores it in ps->cmd to mean "no text", and nextopt()
    # is called with it to mean "no options". Never written.
    "nullstr",
    # var.c: the initial text of IFS and OPTIND. Both are VTEXTFIXED, which is
    # exactly the flag meaning "this text is not heap and is never freed or
    # written"; assigning to either variable allocates new text instead. They
    # are named in varinit[]'s initializer, which is why this matters.
    "defifsvar", "defoptindvar",
    # syntax.c: the character-class tables (generated by mksyntax). Read on
    # every character the parser looks at, written never -- they only lack
    # `const` because mksyntax does not emit it.
    "basesyntax", "dqsyntax", "sqsyntax", "arisyntax", "is_type",
}

# The declaration keywords that may precede the type, and that __thread has to
# go AFTER rather than before: `static __thread int x` is right, and
# `__thread static int x` is a syntax error.
# STATIC and MKINIT are dash's own: shell.h defines STATIC as `static` (and as
# nothing under DEBUG, so it can also be absent), and mkinit.c keys off MKINIT
# to find the declarations it must emit externs for. Both precede the type, so
# both belong here -- `__thread STATIC struct var *vartab[]` does not compile.
LEAD = re.compile(
    r"^(\s*(?:MKINIT|STATIC|static|extern|const|volatile|register)\s+)*")


def read_manifest():
    ext, sta = set(), set()
    with open(MANIFEST) as f:
        for line in f:
            line = line.split("#", 1)[0].split()
            if len(line) == 2:
                (sta if line[0] == "static" else ext).add(line[1])
    return ext, sta


def write_manifest(ext, sta):
    with open(MANIFEST, "w") as f:
        f.write("# dash's mutable globals, as the linker sees them in a build\n"
                "# of the UNCONVERTED tree. Regenerate with\n"
                "#     ninja -C build libdash.a && "
                "tools/dash-tls-rewrite.py --refresh\n"
                "# and only from a pristine deps/dash -- see MANIFEST in that\n"
                "# file for why a half-converted build gives a short list.\n")
        for kind, names in (("extern", ext), ("static", sta)):
            for name in sorted(names):
                f.write("%s %s\n" % (kind, name))


def shared_globals():
    """(external, static) name sets, from the linker's own view."""
    ext, sta = set(), set()
    for entry in sorted(os.listdir(OBJDIR)):
        if not entry.endswith(".o"):
            continue
        nm = subprocess.run(["nm", "-m", os.path.join(OBJDIR, entry)],
                            capture_output=True, text=True).stdout
        for line in nm.splitlines():
            # A common symbol prints `(common) (alignment 2^3) external _name`
            # -- the section and the linkage are not adjacent, so they are two
            # separate tests. Matching them as one string is how bash's tool
            # once reported "nothing shared" while seven things were.
            if not re.search(r"\((?:__DATA,__(?:data|bss|common)|common)\)", line):
                continue
            sym = line.split()[-1]
            if "$tlv$" in sym or not sym.startswith("_"):
                continue
            name = sym[1:]
            # A function-scope static prints as `_func.name`. They are just as
            # much per-shell state as a file-scope one -- init.c's `static char
            # ppid[32]` and trap.c's `static int is_interactive` both survived
            # into the next shell -- but they are not at file scope, so they are
            # kept apart and matched differently below.
            if "." in name:
                name = "." + name.split(".")[-1]
            if name.lstrip(".") in ALLOW:
                continue
            (sta if "non-external" in line else ext).add(name)
    return ext, sta


def skip_blanks(text, i):
    """Advance past whitespace and comments -- the real start of a statement.

    The previous statement's `;` is not where the next one begins: dash writes
    `MKINIT struct parsefile basepf;\t/* top level input file */` and the
    trailing comment sits between the two. Inserting at the raw offset put
    __thread inside that comment's line and left the declaration untouched.
    """
    n = len(text)
    while i < n:
        if text[i].isspace():
            i += 1
        elif text.startswith("/*", i):
            j = text.find("*/", i + 2)
            i = n if j < 0 else j + 2
        elif text.startswith("//", i):
            j = text.find("\n", i)
            i = n if j < 0 else j + 1
        else:
            break
    return i


def mkinit_spans(text):
    """The `#ifdef mkinit ... #endif` regions, which are not compiled.

    dash keeps its per-shell initialisation there as INIT/RESET/FORKRESET
    blocks, and mkinit.c parses them to GENERATE init.c. They contain
    assignments that look like declarations (`INCLUDE <unistd.h>`), and a
    __thread added to one would be copied into the generated file verbatim.
    """
    spans, depth, start = [], 0, None
    for m in re.finditer(r"^#\s*(ifdef|ifndef|if|endif)\b[^\n]*", text, re.M):
        word = m.group(1)
        if word == "endif":
            if depth:
                depth -= 1
                if depth == 0 and start is not None:
                    spans.append((start, m.end()))
                    start = None
        else:
            if depth:
                depth += 1
            elif word == "ifdef" and m.group(0).split()[-1] == "mkinit":
                depth, start = 1, m.start()
    return spans


def statements(text):
    """Yield (start, end) of every file-scope statement ending in ';'.

    Comments and string literals are skipped rather than matched, because dash
    has both a `/* char *trap[NSIG] */` in a comment and a "static" inside a
    string literal, and either one moves every offset after it if mishandled.
    """
    skip = mkinit_spans(text)
    i, n, depth, start = 0, len(text), 0, 0
    while i < n:
        for a, b in skip:
            if a <= i < b:
                i, start = b, b
                break
        c = text[i]
        if c == "/" and i + 1 < n and text[i + 1] == "*":
            i = text.find("*/", i + 2)
            i = n if i < 0 else i + 2
            continue
        if c == "/" and i + 1 < n and text[i + 1] == "/":
            i = text.find("\n", i)
            i = n if i < 0 else i + 1
            continue
        if c in "\"'":
            q, i = c, i + 1
            while i < n and text[i] != q:
                i += 2 if text[i] == "\\" else 1
            i += 1
            continue
        if c == "#" and (i == 0 or text[i - 1] == "\n"):
            # A preprocessor line, continuations and all. Never a declaration,
            # and its braces are not C braces (`#define X {1,2}`).
            #
            # It only ENDS a statement at depth 0. varinit[] has `#if ATTY`
            # inside its initializer, and resetting the start there moved the
            # statement to begin halfway through the braces -- so the
            # definition was left shared while var.h's extern was converted,
            # which is the exact mismatch this conversion exists to avoid.
            while i < n:
                i = text.find("\n", i)
                if i < 0:
                    i = n
                    break
                if text[i - 1] != "\\":
                    i += 1
                    break
                i += 1
            if depth == 0:
                start = i
            continue
        if c in "{([":
            depth += 1
        elif c in "})]":
            depth -= 1
            # A brace closing back to file scope and NOT followed by `;` or `,`
            # ended a FUNCTION DEFINITION (or a typedef), which is not a
            # statement and never terminates in a semicolon. Without this the
            # scan runs on to the next top-level `;` and treats the whole
            # function body as one declaration -- which is how `static void
            # yyerror(const char *s) { sh_error(..., arith_startbuf); }` came
            # back as a declaration of arith_startbuf, and how the real
            # declarations that followed a function (pathopt, job_warning) were
            # swallowed and left shared.
            if c == "}" and depth == 0:
                j = skip_blanks(text, i + 1)
                if j >= n or text[j] not in ";,":
                    i, start = i + 1, i + 1
                    continue
        elif c == ";" and depth == 0:
            yield start, i
            start = i + 1
        i += 1


def declares(stmt, names):
    """The name this statement DEFINES or DECLARES, if it is one of `names`.

    A statement is a data declaration unless the declared name is immediately
    followed by '(' -- which is a function prototype -- so `int foo;`,
    `char *bar[N] = {...};` and `struct output *out1 = &output;` all qualify and
    `int forkshell(struct job *, union node *, int);` does not. A function
    POINTER is `int (*fp)(void);` and its name is not followed by '(' either
    side of the parenthesis, so it is correctly treated as data.
    """
    # Everything before the initializer, with any brace group removed. Both
    # halves matter: `struct var varinit[] = { ..., defifsvar, ... }` must not
    # be read as declaring defifsvar, and `struct jmploc { jmp_buf loc; }`
    # declares a TYPE and no object at all.
    # Comments first. A statement runs from just past the previous `;`, so it
    # carries that line's TRAILING comment -- and `extern int vforked;\t/* Set
    # if we are in the vforked child */` put the word "vforked" inside the next
    # declaration, which is how `void setjobctl(int);` came back as a
    # declaration of vforked.
    stmt = re.sub(r"/\*.*?\*/", " ", stmt, flags=re.S)
    stmt = re.sub(r"//[^\n]*", " ", stmt)
    body = stmt.split("=", 1)[0]
    while True:
        stripped = re.sub(r"\{[^{}]*\}", " ", body)
        if stripped == body:
            break
        body = stripped
    for name in names:
        # EVERY occurrence, not the first. dash names several structs after the
        # object they hold -- `struct output output`, `struct parsefile
        # *parsefile` -- so the first match is the TYPE, and stopping there left
        # both of them shared while everything pointing at them was converted.
        for m in re.finditer(r"\b%s\b" % re.escape(name), body):
            rest = body[m.end():].lstrip()
            if rest.startswith("("):
                continue                   # a prototype, not an object
            # `struct trap { ... }` and `enum x { trap }` name a TYPE or an
            # enumerator, not an object; the tell is the name appearing right
            # after struct/union/enum.
            before = body[:m.start()].rstrip()
            if re.search(r"\b(?:struct|union|enum)$", before):
                continue
            return name
    return None


def main():
    refresh = "--refresh" in sys.argv[1:]
    if refresh or not os.path.exists(MANIFEST):
        if not os.path.isdir(OBJDIR):
            sys.exit("%s: no %s -- build libdash first (ninja -C build)"
                     % (sys.argv[0], OBJDIR))
        ext, sta = shared_globals()
        if not ext and not sta:
            sys.exit("%s: nm found no shared globals at all. That is not a\n"
                     "    clean bill of health, it is a broken query -- either\n"
                     "    the archive is wrong or the tree is already\n"
                     "    converted, and neither is a reason to write an empty\n"
                     "    manifest." % sys.argv[0])
        write_manifest(ext, sta)
        print("wrote %s (%d extern, %d static)"
              % (os.path.relpath(MANIFEST, REPO), len(ext), len(sta)))
        if refresh:
            return
    else:
        ext, sta = read_manifest()
    ext -= ALLOW
    sta -= ALLOW

    changed, count = [], 0
    files = [(d, e) for d in DIRS for e in sorted(os.listdir(d))]
    for vendor, entry in files:
        if not entry.endswith((".c", ".h")):
            continue
        # The generators run on the BUILD host as ordinary programs; they are
        # not part of the shell and a thread-local in one would be noise.
        if entry in ("mkinit.c", "mknodes.c", "mksyntax.c", "aok_mksignames.c"):
            continue
        path = os.path.join(vendor, entry)
        with open(path) as f:
            text = f.read()
        # A static is only visible in its own file; an external has to be found
        # in every file that declares it, headers included.
        here = ext | ({n for n in sta if not n.startswith(".")}
                      if entry.endswith(".c") else set())
        edits = []
        for name in sorted(n[1:] for n in sta if n.startswith(".")):
            for m in re.finditer(
                    r"(?m)^([ \t]+)(static|STATIC)(\s+)(?=[^;\n]*\b%s\b\s*(\[|;|=))"
                    % re.escape(name), text):
                edits.append((m.end(), name))
        for s, e in statements(text):
            stmt = text[s:e]
            if "__thread" in stmt:
                continue
            name = declares(stmt, here)
            if name is None:
                continue
            begin = skip_blanks(text, s)
            lead = LEAD.match(text[begin:e]).end()
            edits.append((begin + lead, name))
        if not edits:
            continue
        edits.sort()
        for off, _ in reversed(edits):
            text = text[:off] + "__thread " + text[off:]
        with open(path, "w") as f:
            f.write(text)
        rel = os.path.relpath(path, VENDOR)
        changed.append("%s (%d)" % (rel, len(edits)))
        count += len(edits)

    print("dash: %d declarations made __thread across %d files"
          % (count, len(changed)))
    for c in changed:
        print("   ", c)
    print("\n%d shared globals remain deliberately shared: %s"
          % (len(ALLOW), " ".join(sorted(ALLOW))))


if __name__ == "__main__":
    main()
